name:                learn-you-a-haskell
version:             0.1.0.0
github:              "Weizilla/learn-you-a-haskell"
license:             BSD3
author:              "Wei Yang"
maintainer:          "wei@weizilla.com"
copyright:           "Copyright: (c) 2018 Wei Yang"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Weizilla/learn-you-a-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- containers

library:
  source-dirs: src

executables:
  learn-you-a-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - learn-you-a-haskell

tests:
  learn-you-a-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - learn-you-a-haskell
